services:
  db:
    image: postgres:18.1-alpine3.23
    container_name: postgres_db
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: tinyurl
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d tinyurl" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: tinyurl-app
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tinyurl
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    depends_on:
      - db
