spring:
  application:
    name: tinyurl
  datasource:
    url: jdbc:postgresql://localhost:5432/tinyurl
    username: test
    password: test

server:
  port: 9000

tinyurl:
  hostname: http://tinyurl.sudosai.in
